### ISSUE TITLE
Introduce a "beta" banner following the successful indexing of all ASpace EAD Documents

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#353] opened 2020-09-01 18:28 UTC
This will be needed in order to provide initial access to the application in the production environment, once we have successfully received the cleaned ArchivesSpace-generated EAD Documents from Lyrasis.

**Comment by tpendragon** [comment] 2020-11-03 19:05
Closed as a duplicate of #386

**Closed by tpendragon** 2020-11-03 19:05 UTC
Labels: enhancement
