### ISSUE TITLE
Users should be able to search by collection identifiers

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#79] opened 2019-11-11 16:50 UTC
This feature was long desired on the PULFA 2.0 application, but due to various constraints, this was never implemented. This might already be supported with the current approach to indexing and Blacklight configuration, but including this in cognitive walkthroughs for user testing might still be desirable.

**Comment by jrgriffiniii** [comment] 2019-12-03 21:16
After discussing this with @faithc, it was confirmed that the immediate need is to ensure that users are able to search by component identifiers (`<c id="...">`). Container-level searching requires a larger discussion of the data model being used in the EAD.

**Comment by jrgriffiniii** [comment] 2020-03-23 19:32
This needs to have acceptance criteria in order to be properly closed.

**Comment by jrgriffiniii** [comment] 2020-03-23 19:34
This can be achieved, where component IDs are already structured in the data with the collection ID prefixed.

**Comment by jrgriffiniii** [comment] 2020-03-23 19:35
**Acceptance criteria:** When users search for "AC044_c0001", the targeted component record is retrieved in the search results.

Please be aware that the padding with 0s is not consistent between collections (users cannot try to guess these).

**Comment by khanhvu98kk** [comment] 2020-03-24 18:17
Resolved by pulibrary/pul_solr#210

**Comment by tpendragon** [comment] 2020-10-06 20:10
Closed as duplicate of #97

**Closed by tpendragon** 2020-10-06 20:10 UTC
Labels: enhancement, user experience
