### ISSUE TITLE
Provide a list of linked authoritative names for finding aids (name authority/identity management)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#110] opened 2020-01-30 06:45 UTC
PULFA 2.0 currently supports identity management by extracting name authorities from EAC-CPF records, and generating the following interface:

![image](https://user-images.githubusercontent.com/1443986/73426254-d5402300-4301-11ea-867f-44c919794d70.png)

![image](https://user-images.githubusercontent.com/1443986/73426284-e7ba5c80-4301-11ea-9648-31662d17e228.png)

Within each name entry, there is a page with a link to the collections which reference the named person:
![image](https://user-images.githubusercontent.com/1443986/73426348-0d476600-4302-11ea-91d7-dac8757fcebb.png)

This interface (or something similar in functionality) should be implemented in PULFALight for names.

**Comment by tpendragon** [comment] 2020-11-19 22:19
Closed as duplicate of #294

**Closed by tpendragon** 2020-11-19 22:19 UTC
Labels: feature
