### ISSUE TITLE
we need a way to get structured access restrictions out of ASpace 

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#370] opened 2020-09-10 14:39 UTC
Summarizing a conversation with @Will-Clements:

ASpace has structured and actionable fields for access restrictions that archivists want to make use of going forward. These don't export as part of the EAD export functionality. Only notes (=strings) do.

ASpace treats the structured access restrictions as properties of the top container. We need a way to get those out so they can be used to automate aspects of the requesting process.

**Comment by regineheberlein** [comment] 2020-09-10 14:49
We will also need a way to merge them back into the data.

**Comment by regineheberlein** [comment] 2020-09-10 14:50
Kamino cloned this issue to [pulibrary/archivesspace-development](https://github.com/pulibrary/archivesspace-development/issues/44)

**Comment by tpendragon** [comment] 2020-11-09 23:12
Closed as duplicate of #429

**Comment by regineheberlein** [comment] 2020-11-10 13:33
This allows specific start and end dates to be attached to an access restriction. My understanding is it's functionality ADAPT wants to make use of going forward (we're not importing data with this structure).

Here is an example I cooked up from a resource record. We'd want to display the "begin" and "end" dates of the restriction. @Will-Clements or @faithc can probably provide more detail.

"rights_restriction"=>{"begin"=>"2019-12-01",
"end"=>"2021-09-23",
"local_access_restriction_type"=>["Restricted"]},
"subnotes"=>[{"jsonmodel_type"=>"note_text",
"content"=>"This is generically restricted",
"publish"=>false}],
"publish"=>false}],
"uri"=>"/repositories/5/resources/635",
"repository"=>{"ref"=>"/repositories/5"}

**Comment by regineheberlein** [comment] 2020-11-10 13:39
<img width="1145" alt="Screen Shot 2020-11-10 at 8 38 50 AM" src="https://user-images.githubusercontent.com/5940563/98681088-494b3500-2330-11eb-920a-cf0b68a6dcfd.png">

**Comment by regineheberlein** [comment] 2020-11-10 13:40
(Sorry, I started responding to this duplicate by mistake, so have reopened this and closed the other)

**Comment by tpendragon** [comment] 2020-11-18 18:24
@regineheberlein @faithc @ccleeton Since we're not importing this data from our old data, can we move this to post-MVP?

**Comment by faithc** [comment] 2020-11-18 19:10
That makes sense to me.

**Comment by ccleeton** [comment] 2020-11-18 19:14
I might need this one explained a bit. Are you all saying we are NOT importing restriction data from the old ead into pulfalight? This would cause a big issue with the ACLU records.

**Comment by Will-Clements** [comment] 2020-11-18 19:18
This is to do with **structured** dates which we don't have in our data as of now. FWIW, in my opinion this can definitely be pushed post-MVP because we won't have structured restrictions until we start creating them in ASpace.

**Comment by faithc** [comment] 2020-11-18 19:27
Yes, @ccleeton, the notes will still be there! :)

**Comment by ccleeton** [comment] 2020-11-18 19:28
Thanks for the clarification! I am still catching up!

**Closed** 2021-03-09 19:08 UTC
Labels: archivesspace
