### ISSUE TITLE
Improve Collection Grouping UI in search result set 

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1015] opened 2022-04-18 12:35 UTC
The gray contrast box highlighting the collection in a search result is too light

**Comment by m-ichelleliu** [comment] 2022-08-02 14:42
Upon closer inspection, the current shade of gray is as dark as it can be in order to meet AAA accessibility standards for the contrast between the blue text and the gray box. Darkening the background color further would require darkening the blue of the text as well, which is a much larger change. We can revisit this ticket if the color becomes a concern in future user testing.

**Comment by sdellis** [comment] 2022-08-02 20:40
The problem is not necessarily that the collection background is too light (although that could be one or part of a possible solution). The problem is that users are not able to distinguish collection-level results from the top "sub" hits within the collections. See [the Highlight Reel ](https://drive.google.com/drive/folders/1SlKD4_kWFiuIMT4WHiu6LzoJ0noouYYe)for more info on the issue.

**Comment by sdellis** [comment] 2022-09-06 18:03
During testing, participants struggled to distinguish between collection-level records and their nested sub-components in the “Group by Collections” search results. Better visual distinction from collection level records (via nesting, contrast, etc), removal of sub-components in these results, or possibly more contrast with the collection-level records would be an improvement. See [the Highlight Reel ](https://drive.google.com/drive/folders/1SlKD4_kWFiuIMT4WHiu6LzoJ0noouYYe)for more info on the issue.

**Comment by sdellis** [comment] 2022-09-06 19:08
Duplicate of #1050 ?

**Closed by sdellis** 2022-09-06 19:08 UTC
Labels: user experience, learning-friendly, usability-test
