### ISSUE TITLE
While looking at the facets on the main search results page, the "More" section is hard to distinguish from the actual results.

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#231] opened 2020-04-07 14:52 UTC
Is there a way to make this more defined? Italicized with ellipses like in current site? Something like that? (see below screenshot to see what it currently looks like and also how it looks on the current site).
![Screen Shot 2020-04-07 at 10 47 24 AM](https://user-images.githubusercontent.com/32106332/78683858-ce173180-78bd-11ea-99ed-d4d8a7df8318.png)
![Screen Shot 2020-04-07 at 10 51 52 AM](https://user-images.githubusercontent.com/32106332/78683865-cfe0f500-78bd-11ea-81c5-8fafa4d270ab.png)

**Comment by ccleeton** [comment] 2022-01-18 15:41
Closing this as a part of our User testing meeting. We could not replicate or see what the issue is. Likely fixed.

**Closed by ccleeton** 2022-01-18 15:41 UTC
Labels: enhancement, user experience, visual design
