### ISSUE TITLE
Query Figgy and display the viewer for any objects linked to the current component ID

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#331] opened 2020-08-10 19:33 UTC
This follows the implementation for https://github.com/PrincetonUniversityLibrary/pulfa/issues/1224, and should reference the work found in https://github.com/pulibrary/orangelight/pull/1495

**Comment by jrgriffiniii** [comment] 2020-08-10 19:34
This is not going to be restricted in scope just to the Toni Morrison Collection, but it was scoped initially to address this as the primary use case.

**Comment by tpendragon** [comment] 2020-11-03 19:48
Closed as duplicate of #389

**Closed by tpendragon** 2020-11-03 19:48 UTC
Labels: feature
